# Generated by Django 3.0.3 on 2020-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200331_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
